#!/usr/bin/env python3
"""
Compound Vault runtime for obsidian-second-brain.

Pure-stdlib helper that adds claude-obsidian-style capabilities to an
obsidian-second-brain vault:
- wiki/hot.md
- wiki/index.md
- wiki/log.md
- source ingest
- BM25-like vault retrieval
- health/lint report

The script is intentionally conservative: it never deletes user notes and it
only writes generated files under wiki/ unless explicitly ingesting a source.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import math
import os
import re
import shutil
import sys
import textwrap
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import Counter, defaultdict
from contextlib import contextmanager
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterator, Sequence

SKIP_DIRS = {
    ".git", ".obsidian", ".trash", "node_modules", "dist", "build", "vendor",
    "__pycache__", ".venv", "venv", ".cache", ".claude", ".codex", ".gemini",
    ".opencode", ".agents", ".compound-locks", ".vault-meta",
    "obsidian-second-brain-plus-overlay",
}
SKIP_FILES = {"AGENTS.md", "DESKTOP-ADAPTERS.md", "INSTALL.md"}
GENERATED_MARKER = "<!-- generated by obsidian-second-brain compound_vault.py -->"
DATE_FMT = "%Y-%m-%d"
DATETIME_FMT = "%Y-%m-%d %H:%M:%S %z"
LOCK_STALE_SECONDS = int(os.environ.get("COMPOUND_LOCK_STALE_SECONDS", "600"))
LOCK_SLEEP_SECONDS = float(os.environ.get("COMPOUND_LOCK_SLEEP_SECONDS", "0.1"))
LOCK_TIMEOUT_SECONDS = float(os.environ.get("COMPOUND_LOCK_TIMEOUT_SECONDS", "30"))
CHUNK_TARGET_CHARS = int(os.environ.get("COMPOUND_CHUNK_TARGET_CHARS", "2400"))
CHUNK_OVERLAP_CHARS = int(os.environ.get("COMPOUND_CHUNK_OVERLAP_CHARS", "300"))
VALID_MODES = {"generic", "lyt", "para", "zettelkasten", "singularity"}
VALID_ROUTE_TYPES = {"source", "entity", "concept", "project", "decision", "question", "session", "research", "source-summary", "comparison", "moc"}
DEFAULT_OLLAMA_URL = "http://127.0.0.1:11434"
DEFAULT_OLLAMA_MODEL = os.environ.get("COMPOUND_OLLAMA_MODEL", "nomic-embed-text")
OLLAMA_TIMEOUT_SEC = float(os.environ.get("COMPOUND_OLLAMA_TIMEOUT_SEC", "3"))
EMBED_TIMEOUT_SEC = float(os.environ.get("COMPOUND_EMBED_TIMEOUT_SEC", "30"))
MAX_OLLAMA_RESPONSE_BYTES = 4 * 1024 * 1024

WIKILINK_RE = re.compile(r"\[\[([^\[\]\|#\r\n]+)(?:#[^\[\]\|\r\n]+)?(?:\|[^\[\]\r\n]+)?\]\]")
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)
WORD_RE = re.compile(r"[A-Za-z0-9_\-]+|[\u4e00-\u9fff]")


def now() -> dt.datetime:
    return dt.datetime.now().astimezone()


def today() -> str:
    return now().strftime(DATE_FMT)


def slugify(text: str, max_len: int = 72) -> str:
    text = text.strip().lower()
    text = re.sub(r"https?://", "", text)
    text = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "-", text)
    text = re.sub(r"-+", "-", text).strip("-")
    if not text:
        text = "note"
    return text[:max_len].strip("-") or "note"


def resolve_vault(path: str | None = None) -> Path:
    raw = path or os.environ.get("OBSIDIAN_VAULT_PATH") or os.getcwd()
    p = Path(raw).expanduser().resolve()
    p.mkdir(parents=True, exist_ok=True)
    return p


def rel(vault: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(vault.resolve()).as_posix()
    except Exception:
        return path.as_posix()


def safe_read(path: Path, limit_bytes: int | None = None) -> str:
    data = path.read_bytes()
    if limit_bytes is not None:
        data = data[:limit_bytes]
    for enc in ("utf-8", "utf-8-sig", "latin-1"):
        try:
            return data.decode(enc)
        except UnicodeDecodeError:
            continue
    return data.decode("utf-8", errors="replace")


def lock_root_for(path: Path) -> Path:
    root = path.parent.resolve()
    while root != root.parent:
        if (root / "wiki").exists() or (root / ".obsidian").exists() or (root / ".git").exists():
            return root / ".compound-locks"
        root = root.parent
    return path.parent.resolve() / ".compound-locks"


def lock_dir_for(path: Path) -> Path:
    digest = hashlib.sha256(str(path.resolve()).encode("utf-8")).hexdigest()
    return lock_root_for(path) / f"{digest}.lock"


def lock_is_stale(lock_dir: Path) -> bool:
    pid_file = lock_dir / "pid"
    if not pid_file.exists():
        return True
    age = time.time() - pid_file.stat().st_mtime
    return age > LOCK_STALE_SECONDS


@contextmanager
def file_lock(path: Path) -> Iterator[None]:
    lock_dir = lock_dir_for(path)
    lock_dir.parent.mkdir(parents=True, exist_ok=True)
    start = time.time()
    while True:
        try:
            lock_dir.mkdir()
            (lock_dir / "pid").write_text(str(os.getpid()), encoding="utf-8")
            (lock_dir / "target").write_text(str(path), encoding="utf-8")
            break
        except FileExistsError:
            if lock_is_stale(lock_dir):
                shutil.rmtree(lock_dir, ignore_errors=True)
                continue
            if time.time() - start >= LOCK_TIMEOUT_SECONDS:
                raise TimeoutError(f"timed out waiting for lock: {path}")
            time.sleep(LOCK_SLEEP_SECONDS)
    try:
        yield
    finally:
        shutil.rmtree(lock_dir, ignore_errors=True)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with file_lock(path):
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(path)


def append_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with file_lock(path):
        with path.open("a", encoding="utf-8") as f:
            f.write(text)


def is_under_nested_git_repo(vault: Path, path: Path) -> bool:
    vault_resolved = vault.resolve()
    current = path.resolve().parent
    while current != vault_resolved and current != current.parent:
        if (current / ".git").exists():
            return True
        current = current.parent
    return False


def iter_markdown(vault: Path, include_generated: bool = True) -> Iterator[Path]:
    for path in vault.rglob("*.md"):
        if is_under_nested_git_repo(vault, path):
            continue
        if path.name in SKIP_FILES and path.parent.resolve() == vault.resolve():
            continue
        parts = set(path.relative_to(vault).parts)
        if parts & SKIP_DIRS:
            continue
        if not include_generated:
            r = rel(vault, path)
            if r in {"wiki/index.md", "wiki/hot.md", "wiki/log.md"} or r.startswith("wiki/meta/"):
                continue
            if is_singularity_mode(vault) and r.startswith("wiki/resources/"):
                continue
            try:
                if GENERATED_MARKER in safe_read(path, limit_bytes=4096):
                    continue
            except Exception:
                continue
        yield path


def tokenize(text: str) -> list[str]:
    tokens = [m.group(0).lower() for m in WORD_RE.finditer(text)]
    # keep English-ish words and single CJK chars; filter very tiny ASCII noise
    return [t for t in tokens if len(t) > 1 or re.match(r"[\u4e00-\u9fff]", t)]


def strip_frontmatter(text: str) -> str:
    return FRONTMATTER_RE.sub("", text, count=1)


def extract_title(path: Path, text: str) -> str:
    for line in strip_frontmatter(text).splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def extract_frontmatter(text: str) -> dict[str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    data: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            data[k.strip()] = v.strip().strip('"')
    return data


def extract_summary(text: str, max_chars: int = 240) -> str:
    body = strip_frontmatter(text)
    lines = []
    for line in body.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("---") or s.startswith("!"):
            continue
        if s.startswith("<!--"):
            continue
        lines.append(s)
        if sum(len(x) for x in lines) >= max_chars:
            break
    summary = " ".join(lines)
    return summary[:max_chars].strip()


def file_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="ignore")).hexdigest()[:16]


def bytes_hash(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:16]


def meta_dir(vault: Path) -> Path:
    return vault / ".vault-meta"


def manifest_path(vault: Path) -> Path:
    return meta_dir(vault) / "compound-manifest.json"


def load_json(path: Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return default


def save_json(path: Path, payload) -> None:
    write_text(path, json.dumps(payload, ensure_ascii=False, indent=2) + "\n")


def load_manifest(vault: Path) -> dict[str, object]:
    manifest = load_json(manifest_path(vault), {"schema_version": 1, "sources": {}})
    if "sources" not in manifest or not isinstance(manifest["sources"], dict):
        manifest["sources"] = {}
    return manifest


def save_manifest(vault: Path, manifest: dict[str, object]) -> None:
    save_json(manifest_path(vault), manifest)


def mode_path(vault: Path) -> Path:
    return meta_dir(vault) / "mode.json"


def mode_config(vault: Path) -> dict[str, object]:
    cfg = load_json(mode_path(vault), {})
    mode = cfg.get("mode", "generic") if isinstance(cfg, dict) else "generic"
    if mode not in VALID_MODES:
        mode = "generic"
    return {"mode": mode, "configured_at": cfg.get("configured_at") if isinstance(cfg, dict) else None}


def set_mode(vault: Path, mode: str) -> dict[str, object]:
    if mode not in VALID_MODES:
        raise ValueError(f"invalid mode: {mode}")
    payload = {
        "schema_version": 1,
        "mode": mode,
        "configured_at": now().isoformat(),
    }
    save_json(mode_path(vault), payload)
    return payload


def safe_title(text: str, fallback: str = "untitled") -> str:
    cleaned = re.sub(r"[/\\\x00-\x1f]+", " ", text).strip()
    cleaned = cleaned.lstrip(".-").strip()
    return cleaned[:96] or fallback


def is_singularity_mode(vault: Path) -> bool:
    return mode_config(vault)["mode"] == "singularity"


DOMAIN_RULES: list[tuple[str, str, tuple[str, ...]]] = [
    ("engineering", "ai-engineering", (
        "clip", "llm", "language model", "foundation model", "test-time adaptation",
        "distribution shift", "vision", "neural", "transformer", "machine learning",
        "deep learning", "retrieval", "embedding", "rag", "agent", "ai ",
    )),
    ("engineering", "python", ("python", "fastapi", "pydantic", "django", "flask")),
    ("engineering", "java", ("java", "spring", "spring boot", "jvm", "maven")),
    ("engineering", "computer-network", ("tcp", "ip", "network", "http", "dns", "routing")),
    ("finance", "markets", ("finance", "market", "asset", "portfolio", "trading", "volatility", "stock")),
    ("medicine", "psychiatry", ("adhd", "psychiatry", "depression", "clinical", "diagnosis")),
    ("medicine", "public-health", ("public health", "epidemiology", "hospital", "patient")),
    ("science", "cognitive-science", ("cognitive", "attention", "memory", "perception")),
    ("business", "strategy", ("strategy", "market positioning", "customer", "revenue", "product-market")),
    ("life", "career", ("career", "interview", "resume", "导师", "advisor")),
]


def infer_domain_subdomain(title: str, text: str = "", source: str = "") -> tuple[str, str]:
    haystack = f"{title}\n{source}\n{text[:8000]}".lower()
    best: tuple[int, str, str] = (0, "engineering", "ai-engineering")
    for domain, subdomain, keywords in DOMAIN_RULES:
        score = sum(1 for keyword in keywords if keyword in haystack)
        if score > best[0]:
            best = (score, domain, subdomain)
    return best[1], best[2]


def top_signal_terms(text: str, limit: int = 12) -> list[str]:
    stop = {
        "the", "and", "for", "with", "that", "this", "from", "are", "was", "were",
        "have", "has", "into", "using", "use", "our", "their", "there", "these",
        "those", "under", "between", "about", "which", "what", "when", "where",
        "一个", "这种", "可以", "以及", "通过", "进行", "问题", "方法", "研究",
    }
    counts = Counter(t for t in tokenize(text) if len(t) > 2 and t not in stop)
    return [term for term, _ in counts.most_common(limit)]


def paper_sidecar_text(path: Path, digest: str) -> str:
    stat = path.stat()
    return textwrap.dedent(f"""\
    # {path.stem}

    ## Original PDF

    - Path: `{path}`
    - Size bytes: {stat.st_size}
    - Hash: `{digest}`

    ## Extracted Text

    No text extraction was performed by `compound_vault.py`. Preserve this companion note as the raw source pointer, then add extracted text or a human reading summary under `source-summaries/`.
    """).strip()


def copy_original_pdf(vault: Path, path: Path, domain: str, subdomain: str, title: str) -> str:
    target = vault / "raw" / "papers" / domain / subdomain / f"{slugify(title)}.pdf"
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists() or bytes_hash(target.read_bytes()) != bytes_hash(path.read_bytes()):
        shutil.copy2(path, target)
    return rel(vault, target)


def route_path(vault: Path, note_type: str, title: str, domain: str | None = None, subdomain: str | None = None) -> str:
    mode = mode_config(vault)["mode"]
    slug = slugify(title)
    raw = safe_title(title, slug)
    if mode == "lyt":
        return f"wiki/notes/{slug}.md"
    if mode == "para":
        mapping = {
            "source": f"wiki/resources/incoming/{slug}.md",
            "entity": f"wiki/resources/people/{raw}.md",
            "concept": f"wiki/resources/concepts/{raw}.md",
            "project": f"wiki/projects/{raw}.md",
            "decision": f"wiki/projects/decisions/{slug}.md",
            "question": f"wiki/resources/questions/{slug}.md",
            "session": f"wiki/projects/inbox/{slug}.md",
            "research": f"wiki/resources/research/{slug}.md",
        }
        return mapping.get(note_type, f"wiki/resources/incoming/{slug}.md")
    if mode == "singularity":
        domain = slugify(domain or infer_domain_subdomain(title)[0])
        subdomain = slugify(subdomain or infer_domain_subdomain(title)[1])
        mapping = {
            "source": f"raw/articles/{domain}/{subdomain}/{slug}.md",
            "entity": f"entities/{domain}/{subdomain}/{slug}.md",
            "concept": f"concepts/{domain}/{subdomain}/{slug}.md",
            "project": f"concepts/{domain}/{subdomain}/{slug}.md",
            "decision": f"queries/{domain}/{subdomain}/{slug}.md",
            "question": f"queries/{domain}/{subdomain}/{slug}.md",
            "session": f"source-summaries/{domain}/{subdomain}/{slug}.md",
            "source-summary": f"source-summaries/{domain}/{subdomain}/{slug}.md",
            "research": f"queries/{domain}/{subdomain}/{slug}.md",
            "comparison": f"comparisons/{domain}/{subdomain}/{slug}.md",
            "moc": f"mocs/{domain}/{subdomain}/{slug}.md",
        }
        return mapping.get(note_type, f"raw/articles/{domain}/{subdomain}/{slug}.md")
    if mode == "zettelkasten":
        zettel_id = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d%H%M%S%f")
        return f"wiki/{zettel_id}-{slug}.md"
    mapping = {
        "source": f"wiki/sources/{slug}.md",
        "entity": f"wiki/entities/{raw}.md",
        "concept": f"wiki/concepts/{raw}.md",
        "project": f"wiki/projects/{raw}.md",
        "decision": f"wiki/decisions/{slug}.md",
        "question": f"wiki/questions/{slug}.md",
        "session": f"wiki/sessions/{slug}.md",
        "research": f"wiki/concepts/{raw}.md",
    }
    return mapping.get(note_type, f"wiki/inbox/{slug}.md")


def write_stub(vault: Path, note_type: str, title: str, source_rel: str, reason: str) -> str:
    path = vault / route_path(vault, note_type, title)
    if path.exists():
        return rel(vault, path)
    source_entry = f"`{source_rel}`" if is_singularity_mode(vault) else f'"[[{Path(source_rel).stem}]]"'
    source_link = f"`{source_rel}`" if is_singularity_mode(vault) else f"`[[{Path(source_rel).stem}]]`"
    directory_hint = {
        "entity": "entities/",
        "concept": "concepts/",
        "project": "concepts/",
        "decision": "queries/",
        "question": "queries/",
        "research": "queries/",
    }.get(note_type, "processed notes")
    body = textwrap.dedent(f"""\
    ---
    title: "{safe_title(title).replace('"', "'")}"
    type: {note_type}
    date: {today()}
    updated: {today()}
    confidence: low
    ai-first: true
    sources:
      - {source_entry}
    ---

    ## For future Claude
    This is a low-confidence {note_type} stub created during deterministic Compound Vault ingest. Expand it after reading {source_link} and replace guesses with sourced claims.

    # {safe_title(title)}

    ## Notes

    - Created from {source_link}.
    - Target layer: `{directory_hint}`.
    - Reason: {reason}

    ## Sources

    - {source_link}
    """)
    write_text(path, body)
    return rel(vault, path)


def extract_ingest_candidates(text: str) -> tuple[list[str], list[str]]:
    candidate_text = strip_frontmatter(text)
    candidate_text = re.split(r"\n\s*(references|bibliography)\s*\n", candidate_text, maxsplit=1, flags=re.I)[0]
    candidate_text = candidate_text[:20000]
    wikilinks = [safe_title(x) for x in WIKILINK_RE.findall(candidate_text)]
    headings = []
    ignored_headings = {
        "raw content", "source", "future claude extraction checklist",
        "purpose in ieh", "original pdf", "extracted text",
    }
    for line in candidate_text.splitlines():
        if line.startswith("## "):
            heading = safe_title(line[3:])
            if not re.fullmatch(r"Page \d+", heading):
                headings.append(heading)
        elif line.startswith("# ") and len(headings) < 1:
            headings.append(safe_title(line[2:]))
    title_case = re.findall(r"\b([A-Z][A-Za-z0-9]+(?:\s+[A-Z][A-Za-z0-9]+){1,4})\b", candidate_text[:8000])
    concepts = []
    for item in headings:
        if item and item.lower() not in ignored_headings:
            concepts.append(item)
    concept_set = {item.lower() for item in concepts}
    entities = []
    ignored_entities = ignored_headings | {
        "abstract machine", "abstract many", "acknowledgements the",
        "additional experimental results", "appendix table",
    }
    for item in wikilinks + title_case:
        item = safe_title(item)
        if item and item.lower() not in ignored_entities and item.lower() not in concept_set:
            entities.append(item)
    return sorted(set(entities))[:12], sorted(set(concepts))[:12]


def distribute_ingest(vault: Path, source_rel: str, text: str) -> dict[str, list[str]]:
    entities, concepts = extract_ingest_candidates(text)
    created_entities = [
        write_stub(vault, "entity", item, source_rel, "candidate entity or proper noun found in source")
        for item in entities
    ]
    created_concepts = [
        write_stub(vault, "concept", item, source_rel, "candidate heading or reusable concept found in source")
        for item in concepts
    ]
    return {"entities": created_entities, "concepts": created_concepts}


def split_sentences(text: str) -> list[str]:
    body = strip_frontmatter(text)
    body = re.sub(r"```.*?```", " ", body, flags=re.S)
    body = re.sub(r"^#+\s+.*$", " ", body, flags=re.M)
    chunks = re.split(r"(?<=[.!?。！？])\s+|\n+\s*[-*]\s+", body)
    sentences = []
    for chunk in chunks:
        sentence = re.sub(r"\s+", " ", chunk).strip(" -\t\r\n")
        if 25 <= len(sentence) <= 420:
            sentences.append(sentence)
    return sentences


def claim_subject(sentence: str) -> str:
    link = WIKILINK_RE.search(sentence)
    if link:
        return safe_title(link.group(1), "unknown")
    proper = re.search(r"\b([A-Z][A-Za-z0-9]+(?:\s+[A-Z][A-Za-z0-9]+){0,4})\b", sentence)
    if proper:
        return safe_title(proper.group(1), "unknown")
    words = tokenize(sentence)
    return " ".join(words[:4]) or "unknown"


def claim_polarity(sentence: str) -> str:
    lowered = sentence.lower()
    negative_markers = [
        " not ", " no ", " never ", " without ", " cannot ", " can't ",
        " deprecated", " removed", " failed", " blocked", " obsolete",
    ]
    if any(marker in f" {lowered} " for marker in negative_markers):
        return "negative"
    return "positive"


def claim_evidence_type(sentence: str) -> str:
    lowered = sentence.lower()
    if re.search(r"\b(19|20)\d{2}[-/]\d{1,2}|\b(19|20)\d{2}\b", sentence):
        return "temporal"
    if re.search(r"\b\d+(?:\.\d+)?%?\b", sentence):
        return "quantitative"
    if any(word in lowered for word in ["must", "should", "required", "requires", "recommend"]):
        return "normative"
    return "factual"


def looks_like_claim(sentence: str) -> bool:
    lowered = sentence.lower()
    predicates = [
        " is ", " are ", " was ", " were ", " has ", " have ", " uses ",
        " supports ", " requires ", " means ", " becomes ", " will ", " can ",
        " should ", " must ", " ships ", " creates ", " updates ",
    ]
    return (
        any(pred in f" {lowered} " for pred in predicates)
        or bool(re.search(r"\b\d+(?:\.\d+)?%?\b", sentence))
        or bool(WIKILINK_RE.search(sentence))
    )


def extract_source_claims(text: str, source_rel: str, max_claims: int = 40) -> list[SourceClaim]:
    claims: list[SourceClaim] = []
    seen = set()
    for sentence in split_sentences(text):
        if not looks_like_claim(sentence):
            continue
        normalized = re.sub(r"\s+", " ", sentence).strip()
        if normalized.lower() in seen:
            continue
        seen.add(normalized.lower())
        digest = file_hash(normalized)
        evidence_type = claim_evidence_type(normalized)
        confidence = "medium" if evidence_type in {"temporal", "quantitative"} else "low"
        claims.append(SourceClaim(
            claim_id=f"claim-{digest}",
            text=normalized,
            subject=claim_subject(normalized),
            polarity=claim_polarity(normalized),
            confidence=confidence,
            evidence_type=evidence_type,
            source_note=source_rel,
        ))
        if len(claims) >= max_claims:
            break
    return claims


def shared_claim_terms(a: str, b: str) -> set[str]:
    stop = {
        "this", "that", "with", "from", "into", "note", "source", "future",
        "claude", "vault", "wiki", "uses", "have", "has", "will", "should",
        "must", "are", "was", "were", "the", "and", "for",
    }
    return {t for t in tokenize(a) if t not in stop} & {t for t in tokenize(b) if t not in stop}


def detect_contradictions(vault: Path, claims: list[SourceClaim], source_rel: str) -> list[ContradictionCandidate]:
    candidates: list[ContradictionCandidate] = []
    notes = load_docs(vault)
    for claim in claims:
        claim_terms = set(tokenize(claim.text))
        if len(claim_terms) < 3:
            continue
        for path, text, info in notes:
            note_rel = rel(vault, path)
            if note_rel == source_rel or note_rel.startswith("wiki/meta/"):
                continue
            for sentence in split_sentences(text)[:80]:
                shared = shared_claim_terms(claim.text, sentence)
                if len(shared) < 3:
                    continue
                other_polarity = claim_polarity(sentence)
                has_contrast = claim.polarity != other_polarity
                changed_status = bool(re.search(r"\b(now|current|currently|formerly|previously|deprecated|replaced|superseded)\b", sentence.lower() + " " + claim.text.lower()))
                if has_contrast or changed_status:
                    candidates.append(ContradictionCandidate(
                        claim_id=claim.claim_id,
                        source_claim=claim.text,
                        candidate_note=note_rel,
                        candidate_text=sentence,
                        reason="polarity mismatch" if has_contrast else "temporal/status change marker",
                        severity="high" if has_contrast else "medium",
                    ))
                    break
            if len([c for c in candidates if c.claim_id == claim.claim_id]) >= 3:
                break
    return candidates[:60]


def proposal_text_for_claim(claim: SourceClaim, source_rel: str) -> str:
    if claim.evidence_type == "temporal":
        return (
            f"- {today()}: {claim.text} "
            f"(source: [[{Path(source_rel).stem}]], confidence: {claim.confidence})"
        )
    return (
        f"- {claim.text} "
        f"(source: [[{Path(source_rel).stem}]], confidence: {claim.confidence})"
    )


def build_patch_proposals(
    vault: Path,
    claims: list[SourceClaim],
    contradictions: list[ContradictionCandidate],
    distributed: dict[str, list[str]],
    source_rel: str,
) -> list[PatchProposal]:
    proposals: list[PatchProposal] = []
    by_claim = {claim.claim_id: claim for claim in claims}
    for candidate in contradictions:
        claim = by_claim.get(candidate.claim_id)
        if not claim:
            continue
        proposals.append(PatchProposal(
            proposal_id=f"proposal-{file_hash(candidate.claim_id + candidate.candidate_note)}",
            target_path=candidate.candidate_note,
            action="review_contradiction",
            claim_id=claim.claim_id,
            rationale=f"{candidate.reason}: source claim conflicts with or changes existing note text.",
            proposed_text=(
                "Add a History or Contradictions section entry:\n"
                f"{proposal_text_for_claim(claim, source_rel)}\n"
                f"- Existing text to review: {candidate.candidate_text}"
            ),
        ))
    distributed_paths = distributed.get("entities", []) + distributed.get("concepts", [])
    for claim in claims[:20]:
        target = ""
        subject_lower = claim.subject.lower()
        for path in distributed_paths:
            if subject_lower and subject_lower in Path(path).stem.lower():
                target = path
                break
        if not target:
            hits = retrieve(vault, claim.subject + " " + " ".join(tokenize(claim.text)[:6]), top_k=5, rerank_mode="lexical")
            for hit in hits:
                if is_safe_patch_target_path(hit.path) and hit.path != source_rel:
                    target = hit.path
                    break
            if not target:
                target = route_path(vault, "concept", claim.subject)
        action = "append_timeline" if claim.evidence_type == "temporal" else "append_evidence"
        proposals.append(PatchProposal(
            proposal_id=f"proposal-{file_hash(claim.claim_id + target + action)}",
            target_path=target,
            action=action,
            claim_id=claim.claim_id,
            rationale=f"Integrate {claim.evidence_type} claim about {claim.subject}.",
            proposed_text=proposal_text_for_claim(claim, source_rel),
        ))
    unique: dict[str, PatchProposal] = {}
    for proposal in proposals:
        unique[proposal.proposal_id] = proposal
    return list(unique.values())[:80]


def write_analysis_artifacts(
    vault: Path,
    source_rel: str,
    text: str,
    distributed: dict[str, list[str]],
) -> dict[str, object]:
    claims = extract_source_claims(text, source_rel)
    contradictions = detect_contradictions(vault, claims, source_rel)
    proposals = build_patch_proposals(vault, claims, contradictions, distributed, source_rel)
    claims_path = vault / "wiki/meta/source-claims-latest.json"
    contradictions_path = vault / "wiki/meta/contradictions-latest.json"
    proposals_json_path = vault / "wiki/meta/patch-proposals-latest.json"
    proposals_md_path = vault / "wiki/meta/patch-proposals-latest.md"
    save_json(claims_path, [asdict(claim) for claim in claims])
    save_json(contradictions_path, [asdict(item) for item in contradictions])
    save_json(proposals_json_path, [asdict(item) for item in proposals])
    write_patch_proposals_markdown(proposals_md_path, source_rel, claims, contradictions, proposals)
    return {
        "claims": [asdict(claim) for claim in claims],
        "contradictions": [asdict(item) for item in contradictions],
        "patch_proposals": [asdict(item) for item in proposals],
        "paths": {
            "claims": rel(vault, claims_path),
            "contradictions": rel(vault, contradictions_path),
            "patch_proposals_json": rel(vault, proposals_json_path),
            "patch_proposals_md": rel(vault, proposals_md_path),
        },
    }


def write_patch_proposals_markdown(
    path: Path,
    source_rel: str,
    claims: list[SourceClaim],
    contradictions: list[ContradictionCandidate],
    proposals: list[PatchProposal],
) -> None:
    lines = [
        "---",
        "title: Latest Patch Proposals",
        "type: patch-proposals",
        f"created: {now().strftime(DATETIME_FMT)}",
        "ai-first: true",
        "---",
        "",
        "## For future Claude",
        "",
        "This generated note proposes reviewable patches after source ingest. Do not apply blindly; read the source and target note first.",
        "",
        "# Latest Patch Proposals",
        "",
        GENERATED_MARKER,
        "",
        "## Source",
        "",
        f"- `{source_rel}`",
        f"- {path_to_wikilink(source_rel)}",
        "",
        "## Summary",
        "",
        f"- Claims extracted: {len(claims)}",
        f"- Contradiction candidates: {len(contradictions)}",
        f"- Patch proposals: {len(proposals)}",
        "",
        "## Proposals",
        "",
    ]
    if proposals:
        for proposal in proposals:
            lines += [
                f"### {proposal.proposal_id}",
                "",
                f"- Target: `{proposal.target_path}`",
                f"- Action: `{proposal.action}`",
                f"- Claim: `{proposal.claim_id}`",
                f"- Rationale: {proposal.rationale}",
                "",
                "```md",
                proposal.proposed_text,
                "```",
                "",
            ]
    else:
        lines.append("None.")
    write_text(path, "\n".join(lines).rstrip() + "\n")


def write_rewrite_plan(
    vault: Path,
    source_rel: str,
    text: str,
    distributed: dict[str, list[str]],
    analysis: dict[str, object] | None = None,
) -> str:
    source_title = extract_title(vault / source_rel, text)
    tokens = Counter(tokenize(text))
    top_terms = [term for term, _ in tokens.most_common(25)]
    relevant_hits = retrieve(vault, " ".join(top_terms[:8]), top_k=8, rerank_mode="lexical")
    plan_path = vault / "wiki/meta/rewrite-plan-latest.md"
    lines = [
        "---",
        f"title: Rewrite Plan for {source_title.replace(chr(34), chr(39))}",
        "type: rewrite-plan",
        f"created: {now().strftime(DATETIME_FMT)}",
        "ai-first: true",
        "---",
        "",
        "## For future Claude",
        "",
        "This generated plan is a work queue for rewriting durable notes after source ingest. Verify every candidate against the source note before editing.",
        "",
        f"# Rewrite Plan: {source_title}",
        "",
        GENERATED_MARKER,
        "",
        "## Source",
        "",
        f"- Source note: `{source_rel}`",
        f"- Wikilink: {path_to_wikilink(source_rel)}",
        "",
        "## Deterministic Candidate Stubs",
        "",
        "### Entities",
        "",
    ]
    lines += [f"- `{p}`" for p in distributed.get("entities", [])] or ["None."]
    lines += ["", "### Concepts", ""]
    lines += [f"- `{p}`" for p in distributed.get("concepts", [])] or ["None."]
    lines += ["", "## Existing Notes to Review", ""]
    if relevant_hits:
        for hit in relevant_hits:
            if hit.path == source_rel or not is_safe_patch_target_path(hit.path):
                continue
            lines.append(f"- `{hit.path}` - {hit.title} - score {hit.score} - {hit.summary}")
    else:
        lines.append("None.")
    lines += [
        "",
        "## Generated Analysis Artifacts",
        "",
    ]
    paths = (analysis or {}).get("paths", {}) if isinstance(analysis, dict) else {}
    if paths:
        for label, artifact_path in paths.items():
            lines.append(f"- {label}: `{artifact_path}`")
    else:
        lines.append("None.")
    lines += [
        "",
        "## Rewrite Instructions",
        "",
        "1. Read the source note first.",
        "2. Read `wiki/meta/source-claims-latest.json` and `wiki/meta/patch-proposals-latest.md`.",
        "3. Read each candidate durable note above.",
        "4. Patch the smallest section that can absorb the new evidence.",
        "5. Preserve old claims in a History or Timeline section when they changed.",
        "6. Add source wikilinks and confidence labels.",
        "7. Do not treat deterministic stubs as verified until the source supports them.",
        "",
        "## Top Terms",
        "",
        ", ".join(top_terms[:25]) or "None.",
    ]
    write_text(plan_path, "\n".join(lines).rstrip() + "\n")
    return rel(vault, plan_path)


@dataclass
class NoteInfo:
    path: str
    title: str
    note_type: str
    mtime: str
    size: int
    links: list[str]
    tags: list[str]
    summary: str
    content_hash: str


@dataclass
class SourceClaim:
    claim_id: str
    text: str
    subject: str
    polarity: str
    confidence: str
    evidence_type: str
    source_note: str


@dataclass
class ContradictionCandidate:
    claim_id: str
    source_claim: str
    candidate_note: str
    candidate_text: str
    reason: str
    severity: str


@dataclass
class PatchProposal:
    proposal_id: str
    target_path: str
    action: str
    claim_id: str
    rationale: str
    proposed_text: str
    status: str = "review-required"


def is_safe_patch_target_path(path: str) -> bool:
    normalized = Path(path).as_posix().lstrip("/")
    if normalized.startswith("../") or "/../" in normalized:
        return False
    unsafe_prefixes = ("wiki/sources/", "wiki/meta/", ".vault-meta/", ".git/", ".obsidian/")
    return normalized.endswith(".md") and not normalized.startswith(unsafe_prefixes)


def resolve_patch_target(vault: Path, target_path: str) -> Path | None:
    if not is_safe_patch_target_path(target_path):
        return None
    target = (vault / target_path).resolve()
    try:
        target.relative_to(vault.resolve())
    except ValueError:
        return None
    return target


def append_under_heading(text: str, heading: str, item: str) -> str:
    lines = text.rstrip().splitlines()
    heading_line = f"## {heading}"
    try:
        idx = lines.index(heading_line)
    except ValueError:
        return text.rstrip() + f"\n\n{heading_line}\n\n{item}\n"

    insert_at = len(lines)
    for i in range(idx + 1, len(lines)):
        if lines[i].startswith("## "):
            insert_at = i
            break
    block = ["", item]
    while insert_at > 0 and lines[insert_at - 1] == "":
        insert_at -= 1
    lines[insert_at:insert_at] = block
    return "\n".join(lines).rstrip() + "\n"


def analyze_note(vault: Path, path: Path) -> NoteInfo:
    text = safe_read(path)
    fm = extract_frontmatter(text)
    links = sorted(set(x.strip() for x in WIKILINK_RE.findall(text) if x.strip()))
    tags = sorted(set(re.findall(r"(?<!\w)#([A-Za-z0-9_\-/\u4e00-\u9fff]+)", text)))
    st = path.stat()
    return NoteInfo(
        path=rel(vault, path),
        title=fm.get("title") or extract_title(path, text),
        note_type=fm.get("type") or infer_note_type(vault, path),
        mtime=dt.datetime.fromtimestamp(st.st_mtime).astimezone().strftime(DATETIME_FMT),
        size=st.st_size,
        links=links,
        tags=tags,
        summary=extract_summary(text),
        content_hash=file_hash(text),
    )


def infer_note_type(vault: Path, path: Path) -> str:
    r = rel(vault, path)
    if r.startswith("raw/articles/") or r.startswith("raw/papers/") or r.startswith("raw/transcripts/"):
        return "source"
    if r.startswith("source-summaries/"):
        return "source-summary"
    if r.startswith("concepts/"):
        return "concept"
    if r.startswith("comparisons/"):
        return "comparison"
    if r.startswith("entities/"):
        return "entity"
    if r.startswith("queries/"):
        return "question"
    if r.startswith("mocs/"):
        return "moc"
    if r.startswith("maintenance/"):
        return "maintenance"
    if r.startswith("wiki/sources/"):
        return "source"
    if r.startswith("wiki/entities/"):
        return "entity"
    if r.startswith("wiki/concepts/"):
        return "concept"
    if r.startswith("wiki/projects/") or r.startswith("projects/"):
        return "project"
    if r.startswith("wiki/decisions/") or r.startswith("decisions/"):
        return "decision"
    if r.startswith("daily/") or r.startswith("journals/"):
        return "daily"
    if r.startswith("wiki/meta/"):
        return "meta"
    if r in {"wiki/index.md", "wiki/hot.md", "wiki/log.md"}:
        return "system"
    return "note"


def first_nonempty_lines(text: str, limit: int = 8) -> list[str]:
    lines = []
    for raw_line in strip_frontmatter(text).splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("---"):
            continue
        if line.startswith("!") or line.startswith("```"):
            continue
        lines.append(line)
        if len(lines) >= limit:
            break
    return lines


def write_source_summary(
    vault: Path,
    source_rel: str,
    title: str,
    source_text: str,
    domain: str = "engineering",
    subdomain: str = "ai-engineering",
    original_rel: str = "",
) -> str:
    if not is_singularity_mode(vault):
        return ""
    path = vault / route_path(vault, "source-summary", title, domain=domain, subdomain=subdomain)
    if path.exists():
        return rel(vault, path)
    excerpt_lines = first_nonempty_lines(source_text, limit=6)
    excerpt = "\n".join(f"> {line[:320]}" for line in excerpt_lines) if excerpt_lines else "> No readable excerpt extracted yet."
    signals = top_signal_terms(source_text)
    signal_line = ", ".join(signals) if signals else "(none yet)"
    raw_link = path_to_wikilink(source_rel)
    source_entries = [f"  - {source_rel}"]
    if original_rel:
        source_entries.insert(0, f"  - {original_rel}")
    source_yaml = "\n".join(source_entries)
    original_line = f"- Original file: `{original_rel}`" if original_rel else "- Original file: same as raw source note"
    body = textwrap.dedent(f"""\
    ---
    title: "{safe_title(title).replace('"', "'")}"
    type: source-summary
    date: {today()}
    updated: {today()}
    domain: {domain}
    subdomain: {subdomain}
    confidence: low
    ai-first: true
    sources:
    {source_yaml}
    ---

    ## For future Claude
    This single-source summary was generated during IEH singularity-mode ingest. Treat it as a reading scaffold, then replace low-confidence bullets with human-checked synthesis after reading the raw source and original file.

    # {safe_title(title)}

    ## Source Trail

    - Raw source note: {raw_link}
    - Raw source path: `{source_rel}`
    {original_line}

    ## Routing

    - Domain: `{domain}`
    - Subdomain: `{subdomain}`
    - Signal terms: {signal_line}

    ## Initial Reading Judgment

    - What problem does this source address?
    - What claims, definitions, methods, or entities should become durable pages?
    - What should be linked into the relevant MOC or query page?
    - Is this source primarily raw material, a paper, a transcript, a study note, or a decision artifact?

    ## Extracted Opening

    {excerpt}

    ## Follow-up

    - [ ] Confirm the title and source identity.
    - [ ] Write a concise Chinese-first summary.
    - [ ] Extract reusable concepts and entities.
    - [ ] Create a query page if the source is part of a learning or research direction.
    - [ ] Add this source to the relevant query page and MOC.
    """).rstrip() + "\n"
    write_text(path, body)
    return rel(vault, path)


def ensure_scaffold(vault: Path) -> None:
    dirs = [
        "wiki", "wiki/sources", "wiki/entities", "wiki/concepts", "wiki/projects",
        "wiki/decisions", "wiki/questions", "wiki/meta", "wiki/inbox", "wiki/notes",
        "wiki/sessions", "wiki/resources", "wiki/resources/incoming",
        "wiki/resources/people", "wiki/resources/concepts", "wiki/resources/questions",
        "wiki/resources/research", ".vault-meta",
        "raw/articles/engineering/ai-engineering", "raw/papers/engineering/ai-engineering",
        "raw/assets", "raw/transcripts",
        "source-summaries/engineering/ai-engineering",
        "concepts/engineering/ai-engineering",
        "comparisons/engineering/ai-engineering",
        "entities/engineering/ai-engineering",
        "queries/engineering/ai-engineering",
        "mocs/engineering/ai-engineering",
        "maintenance",
    ]
    for d in dirs:
        (vault / d).mkdir(parents=True, exist_ok=True)

    files = {
        "wiki/log.md": f"""---\ntitle: Compound Vault Log\ntype: log\ncreated: {today()}\nai-first: true\n---\n\n## For future Claude\nThis append-only log records Compound Vault operations. Read it after `wiki/hot.md` when you need recent mutation history.\n\n# Compound Vault Log\n\n{GENERATED_MARKER}\n\n""",
        "wiki/hot.md": f"""---\ntitle: Hot Cache\ntype: hot-cache\ncreated: {today()}\nai-first: true\n---\n\n## For future Claude\nThis cache is the small recent working set for this vault. Read it first before scanning the full index.\n\n# Hot Cache\n\n{GENERATED_MARKER}\n\nRun `python3 scripts/compound_vault.py hot --vault <vault>` to refresh.\n""",
        "wiki/index.md": f"""---\ntitle: Compound Vault Index\ntype: index\ncreated: {today()}\nai-first: true\n---\n\n## For future Claude\nThis generated index maps vault notes by type and path. Read it after `wiki/hot.md`, then open only the relevant notes.\n\n# Compound Vault Index\n\n{GENERATED_MARKER}\n\nRun `python3 scripts/compound_vault.py index --vault <vault>` to refresh.\n""",
        "wiki/meta/lint-report-latest.md": f"""---\ntitle: Latest Vault Health Report\ntype: health-report\ncreated: {today()}\nai-first: true\n---\n\n## For future Claude\nThis note points to the latest Compound Vault health findings. Refresh it with `compound_vault.py health` before trusting stale results.\n\n# Latest Vault Health Report\n\nNo report yet.\n""",
    }
    for r, content in files.items():
        p = vault / r
        if not p.exists():
            write_text(p, content)


def log_event(vault: Path, event: str, details: str = "") -> None:
    ensure_scaffold(vault)
    line = f"- {now().strftime(DATETIME_FMT)} - {event}"
    if details:
        line += f" - {details}"
    append_text(vault / "wiki/log.md", line + "\n")


def cmd_init(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    ensure_scaffold(vault)
    build_index(vault)
    update_hot(vault, limit=args.limit)
    log_event(vault, "compound-init", "initialized hot/index/log scaffold")
    print(f"Initialized Compound Vault at {vault}")
    print(f"- {vault / 'wiki/index.md'}")
    print(f"- {vault / 'wiki/hot.md'}")
    print(f"- {vault / 'wiki/log.md'}")
    return 0


def build_index(vault: Path) -> list[NoteInfo]:
    ensure_scaffold(vault)
    notes = [analyze_note(vault, p) for p in sorted(iter_markdown(vault, include_generated=False), key=lambda x: rel(vault, x).lower())]
    by_type: dict[str, list[NoteInfo]] = defaultdict(list)
    for n in notes:
        by_type[n.note_type].append(n)

    lines = [
        "---",
        "title: Compound Vault Index",
        "type: index",
        f"updated: {now().strftime(DATETIME_FMT)}",
        "ai-first: true",
        "---",
        "",
        "## For future Claude",
        "",
        "This generated index maps vault notes by type, path, links, tags, and summaries. Read it after `wiki/hot.md`, then open only the relevant source notes.",
        "",
        "# Compound Vault Index",
        "",
        GENERATED_MARKER,
        "",
        "> Retrieval rule: read [[hot]] first, then this index, then only the most relevant notes.",
        "",
        "## Stats",
        "",
        f"- Total markdown notes: {len(notes)}",
        f"- Generated at: {now().strftime(DATETIME_FMT)}",
        "",
        "## Type Summary",
        "",
    ]
    for typ in sorted(by_type):
        lines.append(f"- {typ}: {len(by_type[typ])}")
    lines += ["", "## Notes", ""]
    for typ in sorted(by_type):
        lines += [f"### {typ}", ""]
        for n in sorted(by_type[typ], key=lambda x: x.path.lower()):
            link = path_to_wikilink(n.path)
            summary = f" - {n.summary}" if n.summary else ""
            tags = f" - tags: {', '.join(n.tags[:8])}" if n.tags else ""
            lines.append(f"- {link} (`{n.path}`){summary}{tags}")
        lines.append("")
    write_text(vault / "wiki/index.md", "\n".join(lines).rstrip() + "\n")
    write_text(vault / "wiki/meta/index.json", json.dumps([asdict(n) for n in notes], ensure_ascii=False, indent=2))
    return notes


def path_to_wikilink(path: str) -> str:
    stem = Path(path).stem
    if stem.lower() in {"index", "hot", "log"} and path.startswith("wiki/"):
        stem = Path(path).with_suffix("").as_posix()
    return f"[[{stem}]]"


def cmd_index(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    notes = build_index(vault)
    log_event(vault, "compound-index", f"indexed {len(notes)} notes")
    print(f"Indexed {len(notes)} notes into {vault / 'wiki/index.md'}")
    return 0


def update_hot(vault: Path, limit: int = 20) -> list[NoteInfo]:
    ensure_scaffold(vault)
    all_paths = list(iter_markdown(vault, include_generated=False))
    paths = sorted(all_paths, key=lambda p: p.stat().st_mtime, reverse=True)[:limit]
    notes = [analyze_note(vault, p) for p in paths]
    log_tail = tail_lines(vault / "wiki/log.md", 20)
    lines = [
        "---",
        "title: Hot Cache",
        "type: hot-cache",
        f"updated: {now().strftime(DATETIME_FMT)}",
        "ai-first: true",
        "---",
        "",
        "## For future Claude",
        "",
        "This generated cache lists the most recently changed notes plus recent operation log entries. Use it as the first retrieval stop for session continuity.",
        "",
        "# Hot Cache",
        "",
        GENERATED_MARKER,
        "",
        "> Load this first. It is the small, recent working set for future AI sessions.",
        "",
        "## Recently Changed Notes",
        "",
    ]
    for n in notes:
        summary = f" - {n.summary}" if n.summary else ""
        links = f" - links: {', '.join('[[' + x + ']]' for x in n.links[:5])}" if n.links else ""
        lines.append(f"- {path_to_wikilink(n.path)} (`{n.path}`, {n.mtime}){summary}{links}")
    lines += ["", "## Recent Log", ""]
    lines += log_tail if log_tail else ["No log entries yet."]
    write_text(vault / "wiki/hot.md", "\n".join(lines).rstrip() + "\n")
    return notes


def tail_lines(path: Path, n: int) -> list[str]:
    if not path.exists():
        return []
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    lines = [x for x in lines if x.strip().startswith("-")]
    return lines[-n:]


def cmd_hot(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    notes = update_hot(vault, limit=args.limit)
    log_event(vault, "compound-hot", f"refreshed {len(notes)} hot notes")
    print(f"Updated hot cache with {len(notes)} notes: {vault / 'wiki/hot.md'}")
    return 0


def read_url(url: str, timeout: int = 20, max_bytes: int = 2_000_000) -> tuple[str, str]:
    req = urllib.request.Request(url, headers={"User-Agent": "obsidian-second-brain-plus/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        content_type = resp.headers.get("content-type", "")
        data = resp.read(max_bytes + 1)
        if len(data) > max_bytes:
            data = data[:max_bytes]
    charset = "utf-8"
    m = re.search(r"charset=([^;]+)", content_type)
    if m:
        charset = m.group(1).strip()
    try:
        text = data.decode(charset)
    except Exception:
        text = data.decode("utf-8", errors="replace")
    return text, content_type


def normalize_source_text(raw: str, source: str, content_type: str = "") -> str:
    # Lightweight HTML cleanup, not a full parser; good enough for today-use ingestion.
    text = raw
    if "html" in content_type or "<html" in raw[:1000].lower():
        text = re.sub(r"(?is)<script.*?</script>", "", text)
        text = re.sub(r"(?is)<style.*?</style>", "", text)
        title = re.search(r"(?is)<title[^>]*>(.*?)</title>", text)
        title_text = re.sub(r"\s+", " ", title.group(1)).strip() if title else source
        text = re.sub(r"(?is)<br\s*/?>", "\n", text)
        text = re.sub(r"(?is)</p\s*>", "\n\n", text)
        text = re.sub(r"(?is)<[^>]+>", " ", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        text = re.sub(r"[ \t]{2,}", " ", text)
        text = f"# {title_text}\n\n{text.strip()}"
    return text.strip()


def cmd_ingest(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    ensure_scaffold(vault)
    src = args.source
    source_kind = "url" if re.match(r"https?://", src) else "file"
    content_type = ""
    original_rel = ""
    is_pdf_source = False
    if source_kind == "url":
        raw, content_type = read_url(src)
        base = slugify(src)
        is_pdf_source = "pdf" in content_type.lower() or urllib.parse.urlparse(src).path.lower().endswith(".pdf")
    else:
        p = Path(src).expanduser().resolve()
        if not p.exists():
            print(f"Source not found: {p}", file=sys.stderr)
            return 2
        base = slugify(p.stem)
        is_pdf_source = p.suffix.lower() == ".pdf"
        if is_pdf_source:
            pdf_bytes = p.read_bytes()
            digest = bytes_hash(pdf_bytes)
            title_for_pdf = safe_title(p.stem)
            domain, subdomain = infer_domain_subdomain(title_for_pdf, "", src)
            original_rel = copy_original_pdf(vault, p, domain, subdomain, title_for_pdf)
            raw = paper_sidecar_text(p, digest)
        else:
            raw = safe_read(p, limit_bytes=args.max_bytes)
    text = normalize_source_text(raw, src, content_type)
    title = extract_title(Path(base + ".md"), text) or base
    domain, subdomain = infer_domain_subdomain(title, text, src) if is_singularity_mode(vault) else ("", "")
    if source_kind == "url" and is_pdf_source:
        digest = file_hash(text)
        title_for_pdf = safe_title(title)
        original_rel = f"external-pdf:{src}"
    elif not is_pdf_source:
        digest = file_hash(text)
    manifest = load_manifest(vault)
    source_key = f"{source_kind}:{src}"
    existing = manifest["sources"].get(source_key)
    if existing and existing.get("content_hash") == digest and not args.force:
        print(f"Already ingested unchanged source: {existing.get('source_note')}")
        print("Use --force to re-ingest.")
        return 0
    routed = route_path(vault, "source", f"{today()}-{base}-{digest[:8]}", domain=domain or None, subdomain=subdomain or None)
    out = vault / routed
    ingested_at = now().strftime(DATETIME_FMT)
    if is_singularity_mode(vault):
        checklist = [
            "- [ ] Confirm this belongs under the inferred domain/subdomain.",
            "- [ ] If this is a PDF, verify the preserved original under `raw/papers/`.",
            "- [ ] Complete the matching `source-summaries/` page.",
            "- [ ] Extract entities into `entities/`.",
            "- [ ] Extract concepts or comparisons into `concepts/` or `comparisons/`.",
            "- [ ] Create or update a learning question in `queries/`.",
            "- [ ] Update the relevant `mocs/` page.",
            "- [ ] Flag contradictions or stale claims before applying proposals.",
        ]
    else:
        checklist = [
            "- [ ] Extract entities into `wiki/entities/`",
            "- [ ] Extract concepts into `wiki/concepts/`",
            "- [ ] Link related projects/decisions",
            "- [ ] Flag contradictions or stale claims",
        ]
    body = "\n".join([
        "---",
        f'title: "{title.replace(chr(34), chr(39))}"',
        "type: source",
        f"date: {today()}",
        *( [f"domain: {domain}", f"subdomain: {subdomain}"] if is_singularity_mode(vault) else [] ),
        f'source: "{src.replace(chr(34), chr(39))}"',
        f"source_kind: {source_kind}",
        f"source_format: {'pdf' if is_pdf_source else 'text'}",
        *( [f"original_file: {original_rel}"] if original_rel else [] ),
        f"ingested: {ingested_at}",
        f"content_hash: {digest}",
        "status: raw-ingested",
        "ai-first: true",
        "---",
        "",
        "## For future Claude",
        f"This source note preserves raw material ingested from `{src}`. Extract durable entities, concepts, projects, decisions, and contradictions from it before relying on it as synthesized knowledge.",
        "",
        f"# {title}",
        "",
        "## Source",
        "",
        f"- Original: {src}",
        *( [f"- Preserved original: `{original_rel}`"] if original_rel else [] ),
        *( [f"- Inferred route: `{domain}/{subdomain}`"] if is_singularity_mode(vault) else [] ),
        f"- Ingested: {ingested_at}",
        f"- Hash: `{digest}`",
        "",
        "## Future Claude extraction checklist",
        "",
        *checklist,
        "",
        "## Raw Content",
        "",
        text,
    ]).rstrip() + "\n"
    write_text(out, body)
    source_rel = rel(vault, out)
    summary_rel = write_source_summary(vault, source_rel, title, text, domain=domain or "engineering", subdomain=subdomain or "ai-engineering", original_rel=original_rel)
    distributed = distribute_ingest(vault, source_rel, text) if args.distribute else {"entities": [], "concepts": []}
    build_index(vault)
    build_chunk_index(vault)
    analysis = write_analysis_artifacts(vault, source_rel, text, distributed) if args.analyze_claims else {}
    rewrite_plan = write_rewrite_plan(vault, source_rel, text, distributed, analysis) if args.rewrite_plan else ""
    manifest["sources"][source_key] = {
        "source": src,
        "source_kind": source_kind,
        "content_hash": digest,
        "ingested_at": now().strftime(DATETIME_FMT),
        "source_note": source_rel,
        "source_summary": summary_rel,
        "source_format": "pdf" if is_pdf_source else "text",
        "original_file": original_rel,
        "domain": domain,
        "subdomain": subdomain,
        "distributed": distributed,
        "rewrite_plan": rewrite_plan,
        "analysis": analysis.get("paths", {}) if isinstance(analysis, dict) else {},
    }
    save_manifest(vault, manifest)
    build_index(vault)
    build_chunk_index(vault)
    update_hot(vault, limit=args.hot_limit)
    claim_count = len(analysis.get("claims", [])) if isinstance(analysis, dict) else 0
    contradiction_count = len(analysis.get("contradictions", [])) if isinstance(analysis, dict) else 0
    proposal_count = len(analysis.get("patch_proposals", [])) if isinstance(analysis, dict) else 0
    log_event(vault, "compound-ingest", f"{src} -> {source_rel}; summary={summary_rel or 'none'}; entities={len(distributed['entities'])}; concepts={len(distributed['concepts'])}; claims={claim_count}; contradictions={contradiction_count}; proposals={proposal_count}; rewrite_plan={rewrite_plan or 'none'}")
    print(f"Ingested source into {out}")
    if summary_rel:
        print(f"Source summary: {vault / summary_rel}")
    if rewrite_plan:
        print(f"Rewrite plan: {vault / rewrite_plan}")
    if analysis:
        print(f"Claims: {claim_count}; contradictions: {contradiction_count}; patch proposals: {proposal_count}")
    if distributed["entities"] or distributed["concepts"]:
        print(json.dumps(distributed, ensure_ascii=False, indent=2))
    return 0


@dataclass
class SearchHit:
    path: str
    title: str
    score: float
    matched_terms: list[str]
    summary: str
    snippet: str
    chunk_id: str = ""
    rerank_score: float = 0.0
    rerank_source: str = "bm25-file"


def load_docs(vault: Path) -> list[tuple[Path, str, NoteInfo]]:
    docs = []
    for p in iter_markdown(vault, include_generated=False):
        try:
            text = safe_read(p)
            docs.append((p, text, analyze_note(vault, p)))
        except Exception:
            continue
    return docs


def chunk_text(text: str, target_chars: int = CHUNK_TARGET_CHARS, overlap: int = CHUNK_OVERLAP_CHARS) -> list[str]:
    body = strip_frontmatter(text).strip()
    if not body:
        return []
    paragraphs = re.split(r"\n\s*\n", body)
    chunks: list[str] = []
    current = ""
    for para in paragraphs:
        para = para.strip()
        if not para:
            continue
        if current and len(current) + len(para) + 2 > target_chars:
            chunks.append(current.strip())
            tail = current[-overlap:] if overlap > 0 else ""
            current = (tail + "\n\n" + para).strip()
        else:
            current = (current + "\n\n" + para).strip() if current else para
    if current:
        chunks.append(current.strip())
    return chunks


def build_chunk_index(vault: Path) -> dict[str, object]:
    ensure_scaffold(vault)
    meta = meta_dir(vault)
    chunks_root = meta / "chunks"
    bm25_root = meta / "bm25"
    with file_lock(meta / "chunk-index.lock"):
        if chunks_root.exists():
            shutil.rmtree(chunks_root)
        chunks_root.mkdir(parents=True, exist_ok=True)
        bm25_root.mkdir(parents=True, exist_ok=True)

        docs = {}
        df = Counter()
        postings: dict[str, list[list[object]]] = defaultdict(list)
        chunk_count = 0

        for path in sorted(iter_markdown(vault, include_generated=False), key=lambda p: rel(vault, p).lower()):
            try:
                text = safe_read(path)
                info = analyze_note(vault, path)
            except Exception:
                continue
            page_hash = file_hash(rel(vault, path))
            page_dir = chunks_root / page_hash
            page_dir.mkdir(parents=True, exist_ok=True)
            for idx, raw_chunk in enumerate(chunk_text(text)):
                body_hash = file_hash(raw_chunk)
                chunk_id = f"{page_hash}:{idx}"
                contextualized = f"{info.title}\n{info.note_type}\n{info.summary}\n\n{raw_chunk}"
                chunk_payload = {
                    "chunk_id": chunk_id,
                    "page_address": page_hash,
                    "page_path": rel(vault, path),
                    "page_title": info.title,
                    "chunk_index": idx,
                    "raw_text": raw_chunk,
                    "contextualized_text": contextualized,
                    "body_hash": body_hash,
                }
                chunk_path = page_dir / f"chunk-{idx:03d}.json"
                write_text(chunk_path, json.dumps(chunk_payload, ensure_ascii=False, indent=2) + "\n")
                tokens = tokenize(contextualized)
                tf = Counter(tokens)
                docs[chunk_id] = {
                    "path": rel(vault, chunk_path),
                    "page_path": rel(vault, path),
                    "page_title": info.title,
                    "chunk_index": idx,
                    "dl": len(tokens),
                }
                for term, count in tf.items():
                    df[term] += 1
                    postings[term].append([chunk_id, count])
                chunk_count += 1

        avg_dl = (sum(doc["dl"] for doc in docs.values()) / len(docs)) if docs else 0
        index = {
            "schema_version": 1,
            "params": {"k1": 1.5, "b": 0.75},
            "doc_count": len(docs),
            "chunk_count": chunk_count,
            "avg_dl": avg_dl,
            "updated_at": now().strftime(DATETIME_FMT),
            "vocab": {
                term: {"df": df[term], "postings": postings[term]}
                for term in sorted(df)
            },
            "docs": docs,
        }
        save_json(bm25_root / "index.json", index)
        return index


def load_chunk_payload(vault: Path, rel_path: str) -> dict[str, object] | None:
    path = vault / rel_path
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def query_chunk_index(
    vault: Path,
    query: str,
    top_k: int = 8,
    bm25_top: int = 24,
    rerank_mode: str = "auto",
    allow_remote_ollama: bool = False,
) -> list[SearchHit]:
    index = load_json(meta_dir(vault) / "bm25" / "index.json", None)
    if not index or not index.get("docs"):
        return []
    q_terms = tokenize(query)
    if not q_terms:
        return []
    vocab = index["vocab"]
    docs = index["docs"]
    avg_dl = index.get("avg_dl") or 1.0
    n_docs = index.get("doc_count") or len(docs) or 1
    k1 = index.get("params", {}).get("k1", 1.5)
    b = index.get("params", {}).get("b", 0.75)
    scores: dict[str, float] = defaultdict(float)
    matched: dict[str, set[str]] = defaultdict(set)
    for term in q_terms:
        entry = vocab.get(term)
        if not entry:
            continue
        df = entry["df"]
        idf = math.log(1 + (n_docs - df + 0.5) / (df + 0.5))
        for chunk_id, count in entry["postings"]:
            dl = max(1, docs[chunk_id].get("dl", 1))
            denom = count + k1 * (1 - b + b * dl / avg_dl)
            scores[chunk_id] += idf * (count * (k1 + 1)) / denom
            matched[chunk_id].add(term)
    ranked = sorted(scores.items(), key=lambda item: item[1], reverse=True)[:bm25_top]
    hits: list[SearchHit] = []
    seen_pages: set[str] = set()
    for ranked_item in rerank_chunks(vault, query, ranked, mode=rerank_mode, allow_remote_ollama=allow_remote_ollama):
        chunk_id = ranked_item["chunk_id"]
        score = float(ranked_item["score"])
        doc = docs[chunk_id]
        page_path = doc["page_path"]
        if page_path in seen_pages:
            continue
        payload = load_chunk_payload(vault, doc["path"]) or {}
        page = vault / page_path
        try:
            info = analyze_note(vault, page)
        except Exception:
            continue
        source_text = str(payload.get("raw_text") or "")
        hits.append(SearchHit(
            path=page_path,
            title=info.title,
            score=round(score, 4),
            matched_terms=sorted(matched[chunk_id])[:16],
            summary=info.summary,
            snippet=best_snippet(source_text, sorted(matched[chunk_id])),
            chunk_id=chunk_id,
            rerank_score=round(score, 4),
            rerank_source=str(ranked_item["source"]),
        ))
        seen_pages.add(page_path)
        if len(hits) >= top_k:
            break
    return hits


def rerank_chunks(
    vault: Path,
    query: str,
    ranked: list[tuple[str, float]],
    mode: str = "auto",
    allow_remote_ollama: bool = False,
) -> list[dict[str, object]]:
    if mode not in {"auto", "lexical", "ollama", "none"}:
        mode = "auto"
    if mode == "none":
        return [{"chunk_id": cid, "score": score, "source": "bm25-chunk"} for cid, score in ranked]
    if mode in {"auto", "ollama"}:
        ollama = rerank_chunks_ollama(vault, query, ranked, allow_remote=allow_remote_ollama)
        if ollama:
            return ollama
        if mode == "ollama":
            return [{"chunk_id": cid, "score": score, "source": "bm25-chunk+ollama-unavailable"} for cid, score in ranked]
    return rerank_chunks_lexical(vault, query, ranked)


def rerank_chunks_lexical(vault: Path, query: str, ranked: list[tuple[str, float]]) -> list[dict[str, object]]:
    q_terms = set(tokenize(query))
    if not q_terms:
        return [{"chunk_id": cid, "score": score, "source": "bm25-chunk+lexical-rerank"} for cid, score in ranked]
    index = load_json(meta_dir(vault) / "bm25" / "index.json", {})
    docs = index.get("docs", {})
    rescored: list[dict[str, object]] = []
    for chunk_id, score in ranked:
        doc = docs.get(chunk_id, {})
        payload = load_chunk_payload(vault, doc.get("path", "")) or {}
        text = str(payload.get("contextualized_text") or payload.get("raw_text") or "")
        tokens = set(tokenize(text))
        overlap = len(q_terms & tokens) / max(1, len(q_terms))
        title = str(payload.get("page_title") or "").lower()
        title_boost = 0.15 if any(term in title for term in q_terms) else 0.0
        rescored.append({
            "chunk_id": chunk_id,
            "score": score * (1.0 + overlap + title_boost),
            "source": "bm25-chunk+lexical-rerank",
        })
    return sorted(rescored, key=lambda item: float(item["score"]), reverse=True)


def cosine(a: list[float], b: list[float]) -> float:
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


def ollama_base_url(allow_remote: bool = False) -> str | None:
    url = os.environ.get("OLLAMA_URL", DEFAULT_OLLAMA_URL).rstrip("/")
    parsed = urllib.parse.urlparse(url)
    host = parsed.hostname or ""
    if not allow_remote and host not in {"127.0.0.1", "localhost", "::1"}:
        return None
    return url


def ollama_models(url: str) -> set[str] | None:
    try:
        req = urllib.request.Request(f"{url}/api/tags", method="GET")
        with urllib.request.urlopen(req, timeout=OLLAMA_TIMEOUT_SEC) as resp:
            data = json.loads(resp.read(MAX_OLLAMA_RESPONSE_BYTES))
    except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError):
        return None
    names = set()
    for model in data.get("models", []):
        name = str(model.get("name", ""))
        if name:
            names.add(name)
            names.add(name.split(":")[0])
    return names


def ollama_embed(url: str, model: str, text: str) -> list[float] | None:
    payload = json.dumps({"model": model, "prompt": text}).encode("utf-8")
    req = urllib.request.Request(
        f"{url}/api/embeddings",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=EMBED_TIMEOUT_SEC) as resp:
            data = json.loads(resp.read(MAX_OLLAMA_RESPONSE_BYTES))
    except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError):
        return None
    emb = data.get("embedding")
    if not isinstance(emb, list):
        return None
    return [float(x) for x in emb if isinstance(x, (int, float))]


def load_embed_cache(vault: Path) -> dict[str, list[float]]:
    raw = load_json(meta_dir(vault) / "embed-cache.json", {})
    if not isinstance(raw, dict):
        return {}
    return {str(k): v for k, v in raw.items() if isinstance(v, list)}


def save_embed_cache(vault: Path, cache: dict[str, list[float]]) -> None:
    save_json(meta_dir(vault) / "embed-cache.json", cache)


def rerank_chunks_ollama(
    vault: Path,
    query: str,
    ranked: list[tuple[str, float]],
    allow_remote: bool = False,
) -> list[dict[str, object]] | None:
    url = ollama_base_url(allow_remote)
    if not url:
        return None
    models = ollama_models(url)
    if not models or DEFAULT_OLLAMA_MODEL not in models:
        return None
    q_emb = ollama_embed(url, DEFAULT_OLLAMA_MODEL, query)
    if not q_emb:
        return None
    index = load_json(meta_dir(vault) / "bm25" / "index.json", {})
    docs = index.get("docs", {})
    cache = load_embed_cache(vault)
    dirty = False
    rescored: list[dict[str, object]] = []
    for chunk_id, bm25_score in ranked:
        doc = docs.get(chunk_id, {})
        payload = load_chunk_payload(vault, doc.get("path", "")) or {}
        text = str(payload.get("contextualized_text") or payload.get("raw_text") or "")
        body_hash = str(payload.get("body_hash") or file_hash(text))
        cache_key = f"{DEFAULT_OLLAMA_MODEL}:{body_hash}"
        emb = cache.get(cache_key)
        if not emb:
            emb = ollama_embed(url, DEFAULT_OLLAMA_MODEL, text)
            if not emb:
                rescored.append({
                    "chunk_id": chunk_id,
                    "score": bm25_score,
                    "source": "bm25-chunk+ollama-embed-miss",
                })
                continue
            cache[cache_key] = emb
            dirty = True
        semantic = cosine(q_emb, emb)
        # Keep sparse relevance in the score so semantic near-misses do not dominate.
        final_score = bm25_score * (1.0 + max(0.0, semantic))
        rescored.append({
            "chunk_id": chunk_id,
            "score": final_score,
            "source": f"bm25-chunk+ollama:{DEFAULT_OLLAMA_MODEL}",
        })
    if dirty:
        save_embed_cache(vault, cache)
    return sorted(rescored, key=lambda item: float(item["score"]), reverse=True)


def retrieve(
    vault: Path,
    query: str,
    top_k: int = 8,
    rerank_mode: str = "auto",
    allow_remote_ollama: bool = False,
) -> list[SearchHit]:
    chunk_hits = query_chunk_index(
        vault,
        query,
        top_k=top_k,
        rerank_mode=rerank_mode,
        allow_remote_ollama=allow_remote_ollama,
    )
    if chunk_hits:
        return chunk_hits
    docs = load_docs(vault)
    q_tokens = tokenize(query)
    if not q_tokens:
        return []
    q_counts = Counter(q_tokens)
    doc_tokens = []
    df = Counter()
    for _, text, info in docs:
        weighted = " ".join([
            info.title * 3,
            " ".join(info.tags) * 2,
            text,
        ])
        toks = tokenize(weighted)
        doc_tokens.append(toks)
        df.update(set(toks))
    N = max(1, len(docs))
    avgdl = sum(len(t) for t in doc_tokens) / N if docs else 1
    k1, b = 1.5, 0.75
    hits: list[SearchHit] = []
    for (path, text, info), toks in zip(docs, doc_tokens):
        tf = Counter(toks)
        dl = max(1, len(toks))
        score = 0.0
        matched = []
        for term, qtf in q_counts.items():
            if tf[term] <= 0:
                continue
            matched.append(term)
            idf = math.log(1 + (N - df[term] + 0.5) / (df[term] + 0.5))
            denom = tf[term] + k1 * (1 - b + b * dl / max(1, avgdl))
            score += idf * ((tf[term] * (k1 + 1)) / denom) * qtf
        # Boost AI-first high-value areas.
        r = rel(vault, path)
        if r.startswith("wiki/projects/") or r.startswith("projects/"):
            score *= 1.15
        if r.startswith("wiki/decisions/") or r.startswith("decisions/"):
            score *= 1.12
        if r.startswith("wiki/sources/"):
            score *= 0.92
        if score > 0:
            hits.append(SearchHit(
                path=r,
                title=info.title,
                score=round(score, 4),
                matched_terms=matched[:16],
                summary=info.summary,
                snippet=best_snippet(text, matched),
            ))
    hits.sort(key=lambda h: h.score, reverse=True)
    return hits[:top_k]


def best_snippet(text: str, terms: Sequence[str], max_chars: int = 420) -> str:
    body = strip_frontmatter(text)
    lower = body.lower()
    pos = None
    for t in terms:
        idx = lower.find(t.lower())
        if idx >= 0:
            pos = idx if pos is None else min(pos, idx)
    if pos is None:
        return extract_summary(text, max_chars=max_chars)
    start = max(0, pos - max_chars // 3)
    end = min(len(body), start + max_chars)
    snippet = body[start:end]
    snippet = re.sub(r"\s+", " ", snippet).strip()
    if start > 0:
        snippet = "..." + snippet
    if end < len(body):
        snippet += "..."
    return snippet


def cmd_query(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    ensure_scaffold(vault)
    # Always make sure generated context is fresh enough for today's direct use.
    if args.refresh:
        build_index(vault)
        build_chunk_index(vault)
        update_hot(vault, limit=args.hot_limit)
    hits = retrieve(
        vault,
        args.question,
        top_k=args.top_k,
        rerank_mode=args.rerank,
        allow_remote_ollama=args.allow_remote_ollama,
    )
    out_lines = [
        "---",
        "title: Last Compound Vault Query",
        "type: query-result",
        f"updated: {now().strftime(DATETIME_FMT)}",
        f"query: \"{args.question.replace('"', "'")}\"",
        "ai-first: true",
        "---",
        "",
        "## For future Claude",
        "",
        "This generated note records the latest retrieval candidates for a vault question. Read the listed paths before answering and treat snippets as pointers, not full evidence.",
        "",
        "# Last Compound Vault Query",
        "",
        GENERATED_MARKER,
        "",
        f"Question: {args.question}",
        "",
        "## Retrieval Order",
        "",
        "1. Read `wiki/hot.md`.",
        "2. Read `wiki/index.md` only if hot cache is insufficient.",
        "3. Read the top result notes below.",
        "",
        "## Top Hits",
        "",
    ]
    for i, h in enumerate(hits, 1):
        out_lines += [
            f"### {i}. {h.title}",
            "",
            f"- Path: `{h.path}`",
            f"- Wikilink: {path_to_wikilink(h.path)}",
            f"- Score: {h.score}",
            f"- Chunk: {h.chunk_id or '(file)'}",
            f"- Rerank: {h.rerank_source} ({h.rerank_score})",
            f"- Matched terms: {', '.join(h.matched_terms) if h.matched_terms else 'none'}",
            f"- Summary: {h.summary or '(none)'}",
            f"- Snippet: {h.snippet or '(none)'}",
            "",
        ]
    if not hits:
        out_lines += ["No matching notes found. Create a question note under `wiki/questions/` or ingest sources first.", ""]
    write_text(vault / "wiki/meta/last-query.md", "\n".join(out_lines).rstrip() + "\n")
    print(json.dumps([asdict(h) for h in hits], ensure_ascii=False, indent=2))
    log_event(vault, "compound-query", f"{args.question} -> {len(hits)} hits")
    return 0


def build_link_index(vault: Path) -> tuple[dict[str, Path], dict[str, set[str]], dict[str, set[str]]]:
    aliases: dict[str, Path] = {}
    outlinks: dict[str, set[str]] = defaultdict(set)
    inlinks: dict[str, set[str]] = defaultdict(set)
    for p in iter_markdown(vault, include_generated=False):
        r = rel(vault, p)
        text = safe_read(p)
        aliases[Path(r).stem.lower()] = p
        aliases[Path(r).with_suffix("").as_posix().lower()] = p
        fm = extract_frontmatter(text)
        if fm.get("title"):
            aliases[fm["title"].lower()] = p
    for r in ("wiki/index.md", "wiki/hot.md", "wiki/log.md"):
        p = vault / r
        if p.exists():
            aliases[Path(r).stem.lower()] = p
            aliases[Path(r).with_suffix("").as_posix().lower()] = p
    for p in iter_markdown(vault, include_generated=False):
        r = rel(vault, p)
        text = safe_read(p)
        links = set(x.strip() for x in WIKILINK_RE.findall(text) if x.strip())
        outlinks[r] |= links
        for link in links:
            target_key = link.lower()
            if target_key in aliases:
                inlinks[rel(vault, aliases[target_key])].add(r)
            else:
                # try stem only
                stem_key = Path(link).stem.lower()
                if stem_key in aliases:
                    inlinks[rel(vault, aliases[stem_key])].add(r)
    return aliases, outlinks, inlinks


def health_report(vault: Path) -> dict[str, object]:
    ensure_scaffold(vault)
    note_paths = list(iter_markdown(vault, include_generated=False))
    notes = [analyze_note(vault, p) for p in note_paths]
    aliases, outlinks, inlinks = build_link_index(vault)
    dead_links = []
    for src, links in outlinks.items():
        for link in sorted(links):
            if link.lower() not in aliases and Path(link).stem.lower() not in aliases:
                dead_links.append({"source": src, "link": link})
    orphan_pages = []
    for n in notes:
        if n.note_type in {"system", "log", "index", "hot-cache", "meta"}:
            continue
        if n.path.startswith("wiki/sources/") or n.path.startswith("wiki/meta/"):
            continue
        if not n.links and not inlinks.get(n.path):
            orphan_pages.append(n.path)
    missing_frontmatter = []
    missing_ai_first = []
    for p in note_paths:
        sample = safe_read(p, limit_bytes=4096)
        fm = extract_frontmatter(sample)
        if not FRONTMATTER_RE.match(sample):
            missing_frontmatter.append(rel(vault, p))
        elif fm.get("ai-first") != "true" and not rel(vault, p).startswith("wiki/sources/"):
            missing_ai_first.append(rel(vault, p))
    title_map: dict[str, list[str]] = defaultdict(list)
    for n in notes:
        if n.note_type in {"system", "log", "index", "hot-cache", "meta", "source"} or n.path.startswith("wiki/meta/"):
            continue
        title_map[n.title.lower()].append(n.path)
    duplicate_titles = {
        title: paths for title, paths in title_map.items()
        if title and len(paths) > 1
    }
    generated_staleness = {}
    for r in ["wiki/index.md", "wiki/hot.md", ".vault-meta/bm25/index.json", ".vault-meta/compound-manifest.json"]:
        p = vault / r
        if p.exists():
            age_hours = (now() - dt.datetime.fromtimestamp(p.stat().st_mtime).astimezone()).total_seconds() / 3600
            generated_staleness[r] = round(age_hours, 2)
        else:
            generated_staleness[r] = None
    index_json = vault / "wiki/meta/index.json"
    index_paths = set()
    if index_json.exists():
        try:
            index_paths = {x["path"] for x in json.loads(index_json.read_text(encoding="utf-8"))}
        except Exception:
            index_paths = set()
    actual_paths = {rel(vault, p) for p in note_paths}
    index_missing = sorted(actual_paths - index_paths) if index_paths else sorted(actual_paths)
    manifest = load_manifest(vault)
    manifest_missing = []
    for source_key, item in manifest.get("sources", {}).items():
        source_note = item.get("source_note") if isinstance(item, dict) else None
        if source_note and not (vault / source_note).exists():
            manifest_missing.append({"source": source_key, "source_note": source_note})
    return {
        "generated_at": now().strftime(DATETIME_FMT),
        "note_count": len(notes),
        "dead_links": dead_links,
        "orphan_pages": sorted(orphan_pages),
        "missing_frontmatter": sorted(missing_frontmatter),
        "missing_ai_first": sorted(missing_ai_first),
        "duplicate_titles": duplicate_titles,
        "generated_staleness_hours": generated_staleness,
        "index_missing_paths": index_missing,
        "manifest_missing_sources": manifest_missing,
    }


def write_health_report(vault: Path, report: dict[str, object]) -> Path:
    date = today()
    path = vault / "wiki/meta" / f"lint-report-{date}.md"
    dead_links = report["dead_links"]
    orphan_pages = report["orphan_pages"]
    missing_frontmatter = report["missing_frontmatter"]
    missing_ai_first = report["missing_ai_first"]
    index_missing = report["index_missing_paths"]
    duplicate_titles = report["duplicate_titles"]
    manifest_missing = report["manifest_missing_sources"]
    lines = [
        "---",
        f"title: Vault Health Report {date}",
        "type: health-report",
        f"created: {now().strftime(DATETIME_FMT)}",
        "ai-first: true",
        "---",
        "",
        "## For future Claude",
        "",
        "This generated report lists structural issues found in the vault. Treat it as a repair queue and verify current files before making fixes.",
        "",
        f"# Vault Health Report {date}",
        "",
        GENERATED_MARKER,
        "",
        "## Summary",
        "",
        f"- Notes: {report['note_count']}",
        f"- Dead links: {len(dead_links)}",
        f"- Orphan pages: {len(orphan_pages)}",
        f"- Missing frontmatter: {len(missing_frontmatter)}",
        f"- Missing AI-first marker: {len(missing_ai_first)}",
        f"- Duplicate titles: {len(duplicate_titles)}",
        f"- Index missing paths: {len(index_missing)}",
        f"- Manifest missing sources: {len(manifest_missing)}",
        f"- Generated staleness hours: `{json.dumps(report['generated_staleness_hours'], ensure_ascii=False)}`",
        "",
        "## Dead Links",
        "",
    ]
    if dead_links:
        for item in dead_links[:200]:
            lines.append(f"- `{item['source']}` → `[[{item['link']}]]`")
    else:
        lines.append("None.")
    lines += ["", "## Orphan Pages", ""]
    lines += [f"- `{x}`" for x in orphan_pages[:200]] or ["None."]
    lines += ["", "## Missing Frontmatter", ""]
    lines += [f"- `{x}`" for x in missing_frontmatter[:200]] or ["None."]
    lines += ["", "## Missing AI-first Marker", ""]
    lines += [f"- `{x}`" for x in missing_ai_first[:200]] or ["None."]
    lines += ["", "## Duplicate Titles", ""]
    if duplicate_titles:
        for title, paths in list(duplicate_titles.items())[:100]:
            lines.append(f"- `{title}`: {', '.join('`' + p + '`' for p in paths)}")
    else:
        lines.append("None.")
    lines += ["", "## Index Missing Paths", ""]
    lines += [f"- `{x}`" for x in index_missing[:200]] or ["None."]
    lines += ["", "## Manifest Missing Sources", ""]
    if manifest_missing:
        for item in manifest_missing[:100]:
            lines.append(f"- `{item['source']}` -> `{item['source_note']}`")
    else:
        lines.append("None.")
    text = "\n".join(lines).rstrip() + "\n"
    write_text(path, text)
    write_text(vault / "wiki/meta/lint-report-latest.md", text)
    return path


def cmd_health(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    report = health_report(vault)
    path = write_health_report(vault, report)
    if args.fix_index:
        build_index(vault)
        update_hot(vault)
    log_event(vault, "compound-health", f"report -> {rel(vault, path)}")
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(f"Health report written to {path}")
        print(f"Dead links: {len(report['dead_links'])}")
        print(f"Orphan pages: {len(report['orphan_pages'])}")
        print(f"Missing frontmatter: {len(report['missing_frontmatter'])}")
        print(f"Missing AI-first marker: {len(report['missing_ai_first'])}")
    return 0


def cmd_chunks(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    index = build_chunk_index(vault)
    log_event(vault, "compound-chunks", f"chunks={index.get('chunk_count', 0)} docs={index.get('doc_count', 0)}")
    if args.json:
        print(json.dumps({
            "chunk_count": index.get("chunk_count", 0),
            "doc_count": index.get("doc_count", 0),
            "updated_at": index.get("updated_at"),
            "index": rel(vault, meta_dir(vault) / "bm25/index.json"),
        }, ensure_ascii=False, indent=2))
    else:
        print(f"Chunk index written: {meta_dir(vault) / 'bm25/index.json'}")
        print(f"Chunks: {index.get('chunk_count', 0)}")
    return 0


def write_apply_proposals_report(vault: Path, report: dict[str, object]) -> None:
    json_path = vault / "wiki/meta/apply-proposals-latest.json"
    md_path = vault / "wiki/meta/apply-proposals-latest.md"
    save_json(json_path, report)
    lines = [
        "---",
        "title: Latest Apply Proposals Report",
        "type: apply-proposals-report",
        f"created: {now().strftime(DATETIME_FMT)}",
        "ai-first: true",
        "---",
        "",
        "## For future Claude",
        "",
        "This generated report records which patch proposals were applied, skipped, or left for manual contradiction review.",
        "",
        "# Latest Apply Proposals Report",
        "",
        GENERATED_MARKER,
        "",
        "## Summary",
        "",
        f"- Dry run: {report['dry_run']}",
        f"- Applied: {report['applied']}",
        f"- Skipped: {report['skipped']}",
        f"- Proposal file: `{report['proposal_file']}`",
        "",
        "## Items",
        "",
    ]
    for item in report["items"]:
        lines += [
            f"### {item['proposal_id']}",
            "",
            f"- Status: `{item['status']}`",
            f"- Action: `{item['action']}`",
            f"- Target: `{item['target_path']}`",
            f"- Reason: {item['reason']}",
            "",
        ]
    write_text(md_path, "\n".join(lines).rstrip() + "\n")


def cmd_apply_proposals(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    ensure_scaffold(vault)
    proposal_path = Path(args.proposal_file).expanduser() if args.proposal_file else vault / "wiki/meta/patch-proposals-latest.json"
    if not proposal_path.is_absolute():
        proposal_path = vault / proposal_path
    proposal_path = proposal_path.resolve()
    try:
        proposal_path.relative_to(vault.resolve())
    except ValueError:
        print(f"Proposal file must be inside vault: {proposal_path}", file=sys.stderr)
        return 2
    proposals = load_json(proposal_path, [])
    if not isinstance(proposals, list):
        print(f"Proposal file is not a list: {proposal_path}", file=sys.stderr)
        return 2

    dry_run = not args.apply
    applied = 0
    items: list[dict[str, str]] = []
    for proposal in proposals:
        if not isinstance(proposal, dict):
            continue
        proposal_id = str(proposal.get("proposal_id") or "unknown")
        action = str(proposal.get("action") or "")
        target_path = str(proposal.get("target_path") or "")
        proposed_text = str(proposal.get("proposed_text") or "").strip()
        item = {
            "proposal_id": proposal_id,
            "action": action,
            "target_path": target_path,
            "status": "skipped",
            "reason": "",
        }
        if action == "review_contradiction":
            item["reason"] = "contradiction review requires manual confirmation"
            items.append(item)
            continue
        if action not in {"append_evidence", "append_timeline"}:
            item["reason"] = f"unsupported action: {action}"
            items.append(item)
            continue
        target = resolve_patch_target(vault, target_path)
        if target is None:
            item["reason"] = "unsafe target path"
            items.append(item)
            continue
        if not target.exists():
            item["reason"] = "target file missing; create or review manually first"
            items.append(item)
            continue
        if not proposed_text:
            item["reason"] = "empty proposed_text"
            items.append(item)
            continue
        current = safe_read(target)
        if proposed_text in current:
            item["reason"] = "proposal text already present"
            items.append(item)
            continue

        heading = "Timeline" if action == "append_timeline" else "Evidence"
        item["status"] = "would-apply" if dry_run else "applied"
        item["reason"] = f"append under ## {heading}"
        if not dry_run:
            updated = append_under_heading(current, heading, proposed_text)
            write_text(target, updated)
            applied += 1
        items.append(item)

    report = {
        "generated_at": now().strftime(DATETIME_FMT),
        "dry_run": dry_run,
        "proposal_file": rel(vault, proposal_path),
        "applied": applied,
        "skipped": sum(1 for item in items if item["status"] == "skipped"),
        "items": items,
    }
    write_apply_proposals_report(vault, report)
    if applied:
        build_index(vault)
        build_chunk_index(vault)
        update_hot(vault)
    log_event(vault, "compound-apply-proposals", f"dry_run={dry_run}; applied={applied}; skipped={report['skipped']}")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


def cmd_mode(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    ensure_scaffold(vault)
    if args.mode_cmd == "get":
        print(mode_config(vault)["mode"])
        return 0
    if args.mode_cmd == "set":
        payload = set_mode(vault, args.mode)
        log_event(vault, "compound-mode", f"set mode={args.mode}")
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.mode_cmd == "route":
        print(route_path(vault, args.type, args.name))
        return 0
    return 2


def cmd_log(args: argparse.Namespace) -> int:
    vault = resolve_vault(args.vault)
    log_event(vault, args.event, args.details or "")
    if args.refresh_hot:
        update_hot(vault)
    print("Logged.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Compound Vault helper for obsidian-second-brain")
    p.add_argument("--vault", help="Obsidian vault path. Defaults to OBSIDIAN_VAULT_PATH or cwd.")
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("init", help="Create wiki/hot.md, wiki/index.md, wiki/log.md scaffold")
    sp.add_argument("--limit", type=int, default=20)
    sp.set_defaults(func=cmd_init)

    sp = sub.add_parser("index", help="Rebuild wiki/index.md and wiki/meta/index.json")
    sp.set_defaults(func=cmd_index)

    sp = sub.add_parser("hot", help="Refresh wiki/hot.md")
    sp.add_argument("--limit", type=int, default=20)
    sp.set_defaults(func=cmd_hot)

    sp = sub.add_parser("ingest", help="Ingest a local file or URL into wiki/sources")
    sp.add_argument("source")
    sp.add_argument("--max-bytes", type=int, default=2_000_000)
    sp.add_argument("--hot-limit", type=int, default=20)
    sp.add_argument("--force", action="store_true", help="Re-ingest even when manifest hash is unchanged")
    sp.add_argument("--no-distribute", dest="distribute", action="store_false",
                    help="Only preserve source; skip deterministic entity/concept stubs")
    sp.add_argument("--no-rewrite-plan", dest="rewrite_plan", action="store_false",
                    help="Skip writing wiki/meta/rewrite-plan-latest.md")
    sp.add_argument("--no-analyze-claims", dest="analyze_claims", action="store_false",
                    help="Skip source claim extraction, contradiction candidates, and patch proposals")
    sp.set_defaults(distribute=True)
    sp.set_defaults(rewrite_plan=True)
    sp.set_defaults(analyze_claims=True)
    sp.set_defaults(func=cmd_ingest)

    sp = sub.add_parser("query", help="Return top matching vault notes as JSON and write wiki/meta/last-query.md")
    sp.add_argument("question")
    sp.add_argument("--top-k", type=int, default=8)
    sp.add_argument("--refresh", action="store_true", help="Refresh index/hot before retrieval")
    sp.add_argument("--hot-limit", type=int, default=20)
    sp.add_argument("--rerank", choices=["auto", "lexical", "ollama", "none"], default="auto",
                    help="Rerank strategy for chunk candidates. auto tries local Ollama then lexical.")
    sp.add_argument("--allow-remote-ollama", action="store_true",
                    help="Allow OLLAMA_URL to point off localhost. Page chunks are sent to that endpoint.")
    sp.set_defaults(func=cmd_query)

    sp = sub.add_parser("health", help="Write a vault health/lint report")
    sp.add_argument("--json", action="store_true")
    sp.add_argument("--fix-index", action="store_true", help="Rebuild generated index/hot after reporting")
    sp.set_defaults(func=cmd_health)

    sp = sub.add_parser("chunks", help="Rebuild .vault-meta/chunks and .vault-meta/bm25/index.json")
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=cmd_chunks)

    sp = sub.add_parser("apply-proposals", help="Dry-run or apply safe patch proposals")
    sp.add_argument("--proposal-file", help="Defaults to wiki/meta/patch-proposals-latest.json")
    sp.add_argument("--apply", action="store_true", help="Actually write append_evidence and append_timeline proposals")
    sp.set_defaults(func=cmd_apply_proposals)

    sp = sub.add_parser("mode", help="Get, set, or preview methodology-mode routing")
    mode_sub = sp.add_subparsers(dest="mode_cmd", required=True)
    mode_sub.add_parser("get")
    sp_mode_set = mode_sub.add_parser("set")
    sp_mode_set.add_argument("mode", choices=sorted(VALID_MODES))
    sp_mode_route = mode_sub.add_parser("route")
    sp_mode_route.add_argument("type", choices=sorted(VALID_ROUTE_TYPES))
    sp_mode_route.add_argument("name")
    sp.set_defaults(func=cmd_mode)

    sp = sub.add_parser("log", help="Append to wiki/log.md")
    sp.add_argument("event")
    sp.add_argument("details", nargs="?")
    sp.add_argument("--refresh-hot", action="store_true")
    sp.set_defaults(func=cmd_log)
    return p


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except KeyboardInterrupt:
        return 130
    except Exception as e:
        print(f"compound_vault.py error: {e}", file=sys.stderr)
        if os.environ.get("COMPOUND_DEBUG"):
            raise
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
